import type { Locale } from "./types";

export type FirebaseText = {
  sectionTitle: string;
  help: string;
  signInTitle: string;
  signInHelp: string;
  signOut: string;
  loading: string;
  loadError: string;
  signInError: string;
  notConfigured: string;
  refresh: string;
  notesTitle: string;
  notesHelp: string;
  notesEmpty: string;
  pending: string;
  approved: string;
  approve: string;
  unapprove: string;
  reviewPending: string;
  reviewSendError: string;
  deskSignIn: string;
  deskOpenNote: string;
  contentSignIn: string;
  contentLive: string;
  contentNotLive: string;
  uploadAll: string;
  contentUploaded: string;
  contentSaved: string;
  contentError: string;
};

export const firebaseText: Record<Locale, FirebaseText> = {
  en: {
    sectionTitle: "Message storage (Firebase)",
    help: "Paste the web app config from your Firebase project. These values are public by design; the Firestore rules protect your data. Leave empty to keep messages in this browser only.",
    signInTitle: "Sign in to read messages",
    signInHelp: "Use the admin email and password you created in Firebase Authentication.",
    signOut: "Sign out of Firebase",
    loading: "Loading messages...",
    loadError: "Could not load messages. Check that you are signed in with the admin account and that the Firestore rules are published.",
    signInError: "Sign-in failed. Check the email and password.",
    notConfigured: "Firebase is not set up yet, so these messages are only the ones saved in this browser.",
    refresh: "Refresh",
    notesTitle: "Visitor notes (Firebase)",
    notesHelp: "Notes sent from the site are saved in Firestore and stay hidden until you approve them. Sign in to review them.",
    notesEmpty: "No notes in Firestore yet.",
    pending: "Waiting for approval",
    approved: "Visible on the site",
    approve: "Approve",
    unapprove: "Hide",
    reviewPending: "Thank you! Your note was received and will appear once it has been approved.",
    reviewSendError: "Your note could not be sent. Please try again in a moment.",
    deskSignIn: "Sign in to open the desk",
    deskOpenNote: "Firebase is not set up, so this desk is open and only changes this browser. Add your Firebase settings under Site to protect it with the admin sign-in and to publish changes.",
    contentSignIn: "Sign in to edit places and trip plans",
    contentLive: "Places and trip plans are stored in Firestore. Changes you save here appear on the site straight away, with no redeploy.",
    contentNotLive: "Places and trip plans are not in Firestore yet, so visitors still see the site file. Your first save here uploads everything, or upload it now.",
    uploadAll: "Upload current places and trips to Firestore",
    contentUploaded: "Uploaded to Firestore. The site now reads places and trips from there.",
    contentSaved: "Saved to Firestore. The site is updated.",
    contentError: "Could not save to Firestore. Check that you are signed in as the admin and that the rules are published.",
  },
  fr: {
    sectionTitle: "Stockage des messages (Firebase)",
    help: "Collez la configuration de l'application web de votre projet Firebase. Ces valeurs sont publiques par conception ; les règles Firestore protègent vos données. Laissez vide pour garder les messages dans ce navigateur uniquement.",
    signInTitle: "Connectez-vous pour lire les messages",
    signInHelp: "Utilisez l'e-mail et le mot de passe administrateur créés dans Firebase Authentication.",
    signOut: "Se déconnecter de Firebase",
    loading: "Chargement des messages...",
    loadError: "Impossible de charger les messages. Vérifiez que vous êtes connecté avec le compte administrateur et que les règles Firestore sont publiées.",
    signInError: "Échec de la connexion. Vérifiez l'e-mail et le mot de passe.",
    notConfigured: "Firebase n'est pas encore configuré : ces messages sont uniquement ceux enregistrés dans ce navigateur.",
    refresh: "Actualiser",
    notesTitle: "Notes des visiteurs (Firebase)",
    notesHelp: "Les notes envoyées depuis le site sont enregistrées dans Firestore et restent masquées jusqu'à votre approbation. Connectez-vous pour les examiner.",
    notesEmpty: "Aucune note dans Firestore pour le moment.",
    pending: "En attente d'approbation",
    approved: "Visible sur le site",
    approve: "Approuver",
    unapprove: "Masquer",
    reviewPending: "Merci ! Votre note a bien été reçue et apparaîtra après approbation.",
    reviewSendError: "Votre note n'a pas pu être envoyée. Veuillez réessayer dans un instant.",
    deskSignIn: "Connectez-vous pour ouvrir le bureau",
    deskOpenNote: "Firebase n'est pas configuré : ce bureau est ouvert et ne modifie que ce navigateur. Ajoutez vos paramètres Firebase dans Site pour le protéger par la connexion administrateur et publier les changements.",
    contentSignIn: "Connectez-vous pour modifier les lieux et les itinéraires",
    contentLive: "Les lieux et itinéraires sont stockés dans Firestore. Vos modifications apparaissent tout de suite sur le site, sans redéploiement.",
    contentNotLive: "Les lieux et itinéraires ne sont pas encore dans Firestore : les visiteurs voient donc toujours le fichier du site. Votre première sauvegarde ici envoie tout, ou envoyez-les maintenant.",
    uploadAll: "Envoyer les lieux et itinéraires actuels vers Firestore",
    contentUploaded: "Envoyé vers Firestore. Le site lit désormais les lieux et itinéraires depuis Firestore.",
    contentSaved: "Enregistré dans Firestore. Le site est à jour.",
    contentError: "Enregistrement dans Firestore impossible. Vérifiez que vous êtes connecté en administrateur et que les règles sont publiées.",
  },
  es: {
    sectionTitle: "Almacenamiento de mensajes (Firebase)",
    help: "Pega la configuración de la app web de tu proyecto de Firebase. Estos valores son públicos por diseño; las reglas de Firestore protegen tus datos. Déjalo vacío para guardar los mensajes solo en este navegador.",
    signInTitle: "Inicia sesión para leer los mensajes",
    signInHelp: "Usa el correo y la contraseña de administrador creados en Firebase Authentication.",
    signOut: "Cerrar sesión de Firebase",
    loading: "Cargando mensajes...",
    loadError: "No se pudieron cargar los mensajes. Comprueba que has iniciado sesión con la cuenta de administrador y que las reglas de Firestore están publicadas.",
    signInError: "Error al iniciar sesión. Revisa el correo y la contraseña.",
    notConfigured: "Firebase aún no está configurado, así que estos mensajes son solo los guardados en este navegador.",
    refresh: "Actualizar",
    notesTitle: "Notas de visitantes (Firebase)",
    notesHelp: "Las notas enviadas desde el sitio se guardan en Firestore y permanecen ocultas hasta que las apruebes. Inicia sesión para revisarlas.",
    notesEmpty: "Aún no hay notas en Firestore.",
    pending: "Pendiente de aprobación",
    approved: "Visible en el sitio",
    approve: "Aprobar",
    unapprove: "Ocultar",
    reviewPending: "¡Gracias! Hemos recibido tu nota y aparecerá cuando sea aprobada.",
    reviewSendError: "No se pudo enviar tu nota. Inténtalo de nuevo en un momento.",
    deskSignIn: "Inicia sesión para abrir el escritorio",
    deskOpenNote: "Firebase no está configurado, así que este escritorio está abierto y solo cambia este navegador. Añade tus ajustes de Firebase en Sitio para protegerlo con el acceso de administrador y publicar cambios.",
    contentSignIn: "Inicia sesión para editar lugares y planes de viaje",
    contentLive: "Los lugares y planes de viaje se guardan en Firestore. Los cambios que guardes aquí aparecen en el sitio al instante, sin volver a desplegar.",
    contentNotLive: "Los lugares y planes aún no están en Firestore, así que los visitantes siguen viendo el archivo del sitio. Tu primer guardado aquí lo sube todo, o súbelo ahora.",
    uploadAll: "Subir los lugares y planes actuales a Firestore",
    contentUploaded: "Subido a Firestore. El sitio ahora lee los lugares y planes desde allí.",
    contentSaved: "Guardado en Firestore. El sitio está actualizado.",
    contentError: "No se pudo guardar en Firestore. Comprueba que has iniciado sesión como administrador y que las reglas están publicadas.",
  },
  de: {
    sectionTitle: "Nachrichtenspeicher (Firebase)",
    help: "Fügen Sie die Web-App-Konfiguration Ihres Firebase-Projekts ein. Diese Werte sind absichtlich öffentlich; die Firestore-Regeln schützen Ihre Daten. Leer lassen, um Nachrichten nur in diesem Browser zu speichern.",
    signInTitle: "Anmelden, um Nachrichten zu lesen",
    signInHelp: "Verwenden Sie die Admin-E-Mail und das Passwort aus Firebase Authentication.",
    signOut: "Von Firebase abmelden",
    loading: "Nachrichten werden geladen...",
    loadError: "Nachrichten konnten nicht geladen werden. Prüfen Sie, ob Sie mit dem Admin-Konto angemeldet sind und die Firestore-Regeln veröffentlicht wurden.",
    signInError: "Anmeldung fehlgeschlagen. Prüfen Sie E-Mail und Passwort.",
    notConfigured: "Firebase ist noch nicht eingerichtet; diese Nachrichten stammen nur aus diesem Browser.",
    refresh: "Aktualisieren",
    notesTitle: "Besucher-Notizen (Firebase)",
    notesHelp: "Über die Website gesendete Notizen werden in Firestore gespeichert und bleiben verborgen, bis Sie sie freigeben. Melden Sie sich an, um sie zu prüfen.",
    notesEmpty: "Noch keine Notizen in Firestore.",
    pending: "Wartet auf Freigabe",
    approved: "Auf der Website sichtbar",
    approve: "Freigeben",
    unapprove: "Ausblenden",
    reviewPending: "Danke! Ihre Notiz ist eingegangen und erscheint nach der Freigabe.",
    reviewSendError: "Ihre Notiz konnte nicht gesendet werden. Bitte versuchen Sie es gleich noch einmal.",
    deskSignIn: "Anmelden, um den Tisch zu öffnen",
    deskOpenNote: "Firebase ist nicht eingerichtet, daher ist dieser Tisch offen und ändert nur diesen Browser. Tragen Sie Ihre Firebase-Einstellungen unter Website ein, um ihn mit der Admin-Anmeldung zu schützen und Änderungen zu veröffentlichen.",
    contentSignIn: "Anmelden, um Orte und Reisepläne zu bearbeiten",
    contentLive: "Orte und Reisepläne liegen in Firestore. Gespeicherte Änderungen erscheinen sofort auf der Website, ohne erneutes Deployment.",
    contentNotLive: "Orte und Reisepläne sind noch nicht in Firestore, daher sehen Besucher weiterhin die Website-Datei. Ihr erstes Speichern hier lädt alles hoch, oder laden Sie es jetzt hoch.",
    uploadAll: "Aktuelle Orte und Reisepläne zu Firestore hochladen",
    contentUploaded: "Zu Firestore hochgeladen. Die Website liest Orte und Reisepläne jetzt von dort.",
    contentSaved: "In Firestore gespeichert. Die Website ist aktuell.",
    contentError: "Speichern in Firestore fehlgeschlagen. Prüfen Sie, ob Sie als Admin angemeldet sind und die Regeln veröffentlicht wurden.",
  },
  ru: {
    sectionTitle: "Хранение сообщений (Firebase)",
    help: "Вставьте конфигурацию веб-приложения из проекта Firebase. Эти значения публичны по замыслу; данные защищают правила Firestore. Оставьте пустым, чтобы хранить сообщения только в этом браузере.",
    signInTitle: "Войдите, чтобы читать сообщения",
    signInHelp: "Используйте адрес и пароль администратора, созданные в Firebase Authentication.",
    signOut: "Выйти из Firebase",
    loading: "Загрузка сообщений...",
    loadError: "Не удалось загрузить сообщения. Убедитесь, что вы вошли под учётной записью администратора и правила Firestore опубликованы.",
    signInError: "Не удалось войти. Проверьте адрес и пароль.",
    notConfigured: "Firebase ещё не настроен, поэтому здесь только сообщения, сохранённые в этом браузере.",
    refresh: "Обновить",
    notesTitle: "Заметки посетителей (Firebase)",
    notesHelp: "Заметки с сайта сохраняются в Firestore и остаются скрытыми, пока вы их не одобрите. Войдите, чтобы просмотреть их.",
    notesEmpty: "В Firestore пока нет заметок.",
    pending: "Ожидает одобрения",
    approved: "Показывается на сайте",
    approve: "Одобрить",
    unapprove: "Скрыть",
    reviewPending: "Спасибо! Ваша заметка получена и появится после одобрения.",
    reviewSendError: "Не удалось отправить заметку. Попробуйте ещё раз чуть позже.",
    deskSignIn: "Войдите, чтобы открыть стол",
    deskOpenNote: "Firebase не настроен, поэтому стол открыт и меняет только этот браузер. Добавьте настройки Firebase в разделе «Сайт», чтобы защитить его входом администратора и публиковать изменения.",
    contentSignIn: "Войдите, чтобы редактировать места и маршруты",
    contentLive: "Места и маршруты хранятся в Firestore. Сохранённые здесь изменения сразу появляются на сайте, без повторной публикации.",
    contentNotLive: "Места и маршруты пока не в Firestore, поэтому посетители видят файл сайта. Первое сохранение здесь загрузит всё, или загрузите сейчас.",
    uploadAll: "Загрузить текущие места и маршруты в Firestore",
    contentUploaded: "Загружено в Firestore. Теперь сайт читает места и маршруты оттуда.",
    contentSaved: "Сохранено в Firestore. Сайт обновлён.",
    contentError: "Не удалось сохранить в Firestore. Проверьте, что вы вошли как администратор и правила опубликованы.",
  },
  zh: {
    sectionTitle: "留言存储（Firebase）",
    help: "粘贴 Firebase 项目的网页应用配置。这些值本身就是公开的，数据由 Firestore 规则保护。留空则仅在此浏览器中保存留言。",
    signInTitle: "登录后查看留言",
    signInHelp: "请使用在 Firebase Authentication 中创建的管理员邮箱和密码。",
    signOut: "退出 Firebase",
    loading: "正在加载留言...",
    loadError: "无法加载留言。请确认已使用管理员账号登录，并且已发布 Firestore 规则。",
    signInError: "登录失败，请检查邮箱和密码。",
    notConfigured: "尚未设置 Firebase，这里只显示保存在此浏览器中的留言。",
    refresh: "刷新",
    notesTitle: "访客笔记（Firebase）",
    notesHelp: "网站提交的笔记会保存到 Firestore，在你批准之前不会显示。请登录后审核。",
    notesEmpty: "Firestore 中还没有笔记。",
    pending: "等待审核",
    approved: "已在网站显示",
    approve: "批准",
    unapprove: "隐藏",
    reviewPending: "谢谢！我们已收到你的笔记，批准后会显示在网站上。",
    reviewSendError: "笔记发送失败，请稍后再试。",
    deskSignIn: "登录后进入管理台",
    deskOpenNote: "尚未设置 Firebase，所以管理台处于开放状态，只会改动当前浏览器。在“站点”中填写 Firebase 设置，即可用管理员登录保护它并发布更改。",
    contentSignIn: "登录后编辑景点和行程",
    contentLive: "景点和行程存储在 Firestore。你在这里保存的更改会立即显示在网站上，无需重新部署。",
    contentNotLive: "景点和行程尚未存入 Firestore，访客看到的仍是网站文件。首次在此保存时会一并上传，也可以现在上传。",
    uploadAll: "将当前景点和行程上传到 Firestore",
    contentUploaded: "已上传到 Firestore，网站现在从 Firestore 读取景点和行程。",
    contentSaved: "已保存到 Firestore，网站已更新。",
    contentError: "无法保存到 Firestore。请确认已用管理员账号登录，并已发布规则。",
  },
  ja: {
    sectionTitle: "メッセージの保存先（Firebase）",
    help: "Firebase プロジェクトの Web アプリ設定を貼り付けてください。これらの値は公開前提で、データは Firestore ルールで保護されます。空欄の場合、メッセージはこのブラウザにのみ保存されます。",
    signInTitle: "ログインしてメッセージを読む",
    signInHelp: "Firebase Authentication で作成した管理者のメールとパスワードを使用してください。",
    signOut: "Firebase からログアウト",
    loading: "メッセージを読み込み中...",
    loadError: "メッセージを読み込めませんでした。管理者アカウントでログインしていること、Firestore ルールが公開されていることを確認してください。",
    signInError: "ログインに失敗しました。メールとパスワードを確認してください。",
    notConfigured: "Firebase が未設定のため、ここにはこのブラウザに保存されたメッセージのみ表示されます。",
    refresh: "更新",
    notesTitle: "訪問者のノート（Firebase）",
    notesHelp: "サイトから送られたノートは Firestore に保存され、承認するまで表示されません。ログインして確認してください。",
    notesEmpty: "Firestore にはまだノートがありません。",
    pending: "承認待ち",
    approved: "サイトに表示中",
    approve: "承認",
    unapprove: "非表示",
    reviewPending: "ありがとうございます。ノートを受け取りました。承認後に表示されます。",
    reviewSendError: "ノートを送信できませんでした。しばらくしてからもう一度お試しください。",
    deskSignIn: "ログインして管理机を開く",
    deskOpenNote: "Firebase が未設定のため、この管理机は開いた状態で、このブラウザだけが変更されます。「サイト」で Firebase の設定を入力すると、管理者ログインで保護され、変更を公開できます。",
    contentSignIn: "ログインして場所と旅程を編集",
    contentLive: "場所と旅程は Firestore に保存されています。ここで保存した変更は再デプロイなしですぐにサイトへ反映されます。",
    contentNotLive: "場所と旅程はまだ Firestore にないため、訪問者にはサイトのファイルが表示されます。ここで最初に保存するとすべてアップロードされます。今すぐアップロードすることもできます。",
    uploadAll: "現在の場所と旅程を Firestore にアップロード",
    contentUploaded: "Firestore にアップロードしました。サイトは Firestore から場所と旅程を読み込みます。",
    contentSaved: "Firestore に保存しました。サイトが更新されました。",
    contentError: "Firestore に保存できませんでした。管理者でログインしていること、ルールが公開されていることを確認してください。",
  },
};
